language: csharp
sudo: false
mono:
  - beta
env:
  - MODE=syntax
  - MODE=python
  - MODE=node
addons:
  apt:
    sources:
    - deadsnakes
    packages:
    # packages for python
    - python3.5
install:
  - wget https://bootstrap.pypa.io/get-pip.py -O /tmp/get-pip.py
  - python3.5 /tmp/get-pip.py --user
  - pip3.5 install -r ./SwaggerToSdk/requirements.txt --user
  - . $HOME/.nvm/nvm.sh
  - nvm install stable
  - nvm use stable
  - npm install	
script:
  - if [[ $MODE == 'python' ]]; then python3.5 ./SwaggerToSdk/SwaggerToSdk.py AutorestCI/azure-sdk-for-python --pr-repo-id Azure/azure-sdk-for-python -o dev -v; fi
  - if [[ $MODE == 'node' ]]; then python3.5 ./SwaggerToSdk/SwaggerToSdk.py AutorestCI/azure-sdk-for-node --pr-repo-id Azure/azure-sdk-for-node -o autorest -v; fi
  - if [[ $MODE == 'syntax' ]]; then npm test; fi
